config/routes.rb
Rails.application.routes.draw do
  resources :notes
  resources :registrations
  resources :sessions
  resources :passwords
  resources :password_resets
  root 'sessions#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  # makes Current.user accessible in view files.
  attribute :user
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  validates :title, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :notes
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
  validates :password, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    # finds user with session data and stores it if present
    Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def require_user_logged_in!
    # allows only logged in user
    redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to session_path(Current.user.id), notice: "Note was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /notes/1
  def update
    if @note.update(note_params)
      redirect_to session_path(Current.user.id), notice: "Note was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /notes/1
  def destroy
    @note.destroy
    redirect_to session_path(Current.user.id), notice: "Note was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :body, :user_id)
    end
end

app/controllers/password_resets_controller.rb
# frozen_string_literal: true

class PasswordResetsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])
    if @user.present?
      # send email
      PasswordMailer.with(user: @user).reset.deliver_later
    end
    redirect_to root_path
  end

  def edit
    # finds user with a valid token
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to sessions_url, alert: 'Your token has expired. Please try again.'
  end

  def update
    # updates user's password
    @user = User.find_signed!(params[:token], purpose: 'password_reset')
    if @user.update(password_params)
      redirect_to sessions_url, notice: 'Your password was reset successfuly'
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/passwords_controller.rb
# frozen_string_literal: true

class PasswordsController < ApplicationController
  # allows only logged in users
  before_action :require_user_logged_in!

  def edit; end

  def update
    # update the user password
    if Current.user.update(password_params)
      redirect_to session_path(Current.user.id), notice: 'Password Updated'
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController

  def index; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # WelcomeMailer.with(user: @user).welcome_email.deliver_now
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Successfully created account'
    elsif User.present?
      flash.now[:alert] = 'That email is already taken, please use a different email.'
      render :new
    else
      p User.exists?(email: params[:email])
      flash.now[:alert] = 'Please fill out the form completely and try again.'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController

  def home; end

  def index; end

  def show
    # gets all of the users notes
    @user = User.find(params[:id])
    @notes = @user.notes
    unless session[:user_id] == @user.id
      flash[:alert] = "You don't have access to that account!"
      redirect_to session_path(session[:user_id])
      return
    end
  end

  def create
    user = User.find_by(email: params[:email])
    # find the existing user, check to see if the user can be authenticated
    if user.present? && user.authenticate(params[:password])
      # set up a user.id session
      session[:user_id] = user.id
      redirect_to session_path(user.id), notice: 'Logged in successfully'
    else
      flash.now[:alert] = 'Invalid email or password'
      render :index
    end
  end

  def destroy
    # delete the user session and log out
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <title>Note+</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
  </head>
  <body>
    
    <%= yield %>

  </body>
</html>

app/views/notes/_form.html.erb
<div class="tile is-ancestor mt-6">
  <div class="tile"></div>
  <div class="tile is-7">
    <div class="tile is-parent">
      <article class="tile is-child notification is-info">
        <p class="title">Note</p>
        <%= form_with(model: note) do |f| %>
        <% if note.errors.any? %>
        <div id="error_explanation" class="notification is-danger">
          <h2>
            <%= pluralize(note.errors.count, "error") %>
            prohibited this note from being saved:
          </h2>
          <ul>
            <% note.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        <%= f.hidden_field :user_id, value: Current.user.id %>
        <div class="field">
          <%= f.label :title, class:"label" %>
          <div class="control">
            <%= f.text_area :title, class:"input", maxlength: 30 %>
          </div>
        </div>

        <div class="field">
          <%= f.label :body, class:"label" %>
          <div class="control">
            <%= f.text_area :body, class:"textarea", placeholder: "e.g. Hello world", maxlength: 1000 %>
          </div>
        </div>

        <div class="field is-grouped is-grouped-centered mt-5">
          <div class="actions control">
            <%= f.submit 'Submit', class:"button is-link" %>
          </div>
          <div class="control">
            <%= link_to 'Back', session_path(Current.user.id), class:"button is-link is-light" %>
          </div>
        </div>
        <% end %>
      </article>
    </div>
  </div>
  <div class="tile"></div>
</div>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

app/views/password_resets/edit.html.erb
<h1>Reset your password?</h1>
<%= form_with model: @user, url: edit_password_reset_path(token: params[:token]) do |f| %>
  <p>
    <%= f.label 'Password:' %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label 'Password Confirmation:' %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit 'Reset Password' %>
  </p>
<% end %>

app/views/password_resets/new.html.erb
<div class="tile is-ancestor mt-6">
  <div class="tile"></div>
  <div class="tile is-7">
    <div class="tile is-parent">
      <article class="tile is-child notification is-info">
        <p class="title">Forgot Password?</p>
        <%= form_with url: password_resets_path do |f| %>
        <div class="field">
          <%= f.label 'Email:', class:"label" %>
          <div class="control has-icons-left has-icons-right">
            <%= f.text_field :email, id: 'email', class:"input", placeholder:"Email input", value:"hello@" %>
            <span class="icon is-small is-left">
              <i class="fas fa-envelope"></i>
            </span>
          </div>
        </div>
        <div class="field is-grouped is-grouped-centered mt-5">
          <div class="control">
            <%= f.submit 'Reset Password', class:"button is-link" %>
          </div>
          <div class="control">
            <%= link_to 'Cancel', sessions_path, class:"button is-link is-light" %>
          </div>
        </div>
        <% end %>
      </article>
    </div>
  </div>
  <div class="tile"></div>
</div>